# Generated by Django 5.2.13 on 2026-04-21 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0003_classe_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=20, unique=True, verbose_name='Année scolaire')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='FraisScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField(choices=[(1, '1er Trimestre'), (2, '2ème Trimestre'), (3, '3ème Trimestre')], verbose_name='Trimestre')),
                ('type_frais', models.CharField(choices=[('inscription', "Frais d'inscription"), ('minerval', 'Minerval'), ('uniforme', 'Uniforme'), ('examen', "Frais d'examen"), ('bibliotheque', 'Bibliothèque'), ('activite', 'Activité parascolaire'), ('cantine', 'Cantine'), ('transport', 'Transport'), ('autre', 'Autre')], max_length=50, verbose_name='Type de frais')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total à payer')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='frais_scolaires.anneescolaire', verbose_name='Année scolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_inscription', to='eleves.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Frais scolaire',
                'verbose_name_plural': 'Frais scolaires',
                'unique_together': {('eleve', 'annee_scolaire', 'trimestre', 'type_frais')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now, verbose_name='Date de paiement')),
                ('mode_paiement', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('banque', 'Virement bancaire'), ('cheque', 'Chèque'), ('carte', 'Carte bancaire')], max_length=50, verbose_name='Mode de paiement')),
                ('reference', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Numéro de reçu')),
                ('statut', models.CharField(choices=[('valide', 'Validé'), ('annule', 'Annulé'), ('en_attente', 'En attente')], default='valide', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='eleves.eleve', verbose_name='Élève')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='frais_scolaires.fraisscolaire', verbose_name='Frais concerné')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='TarifFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_primaire', models.CharField(blank=True, max_length=20, null=True, verbose_name='Classe primaire')),
                ('classe_humanite', models.CharField(blank=True, max_length=30, null=True, verbose_name='Classe humanité')),
                ('option_humanite', models.CharField(blank=True, max_length=50, null=True, verbose_name='Option (section)')),
                ('niveau', models.CharField(choices=[('primaire', 'Primaire'), ('humanite', 'Humanité')], max_length=20, verbose_name='Niveau')),
                ('trimestre', models.IntegerField(choices=[(1, '1er Trimestre'), (2, '2ème Trimestre'), (3, '3ème Trimestre')], verbose_name='Trimestre')),
                ('type_frais', models.CharField(choices=[('inscription', "Frais d'inscription"), ('minerval', 'Minerval'), ('uniforme', 'Uniforme'), ('examen', "Frais d'examen"), ('bibliotheque', 'Bibliothèque'), ('activite', 'Activité parascolaire'), ('cantine', 'Cantine'), ('transport', 'Transport'), ('autre', 'Autre')], max_length=50, verbose_name='Type de frais')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='frais_scolaires.anneescolaire', verbose_name='Année scolaire')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
                'unique_together': {('niveau', 'classe_primaire', 'classe_humanite', 'option_humanite', 'trimestre', 'type_frais', 'annee_scolaire')},
            },
        ),
    ]
