# Generated by Django 4.2.29 on 2026-04-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais_scolaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tariffrais',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tariffrais',
            name='classe_maternel',
            field=models.CharField(blank=True, choices=[('1ere_maternelle', '1ère maternelle'), ('2eme_maternelle', '2ème maternelle'), ('3eme_maternelle', '3ème maternelle')], max_length=20, null=True, verbose_name='Classe maternelle'),
        ),
        migrations.AlterField(
            model_name='tariffrais',
            name='niveau',
            field=models.CharField(choices=[('maternel', 'Maternel'), ('primaire', 'Primaire'), ('humanite', 'Humanité')], max_length=20, verbose_name='Niveau'),
        ),
        migrations.AlterUniqueTogether(
            name='tariffrais',
            unique_together={('niveau', 'classe_maternel', 'classe_primaire', 'classe_humanite', 'option_humanite', 'trimestre', 'type_frais', 'annee_scolaire')},
        ),
    ]
