# Generated by Django 5.2.13 on 2026-04-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais_scolaires', '0002_alter_tariffrais_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraisscolaire',
            name='type_frais',
            field=models.CharField(choices=[('inscription', "Frais d'inscription"), ('minerval', 'Minerval'), ('uniforme', 'Uniforme'), ('examen', "Frais d'examen"), ('activite', 'Activité parascolaire'), ('ecusson', 'Ecusson'), ('tenasosp', 'Tenasosp'), ('dissertation', 'Dissertation'), ('exetat', 'Exetat'), ('cahier_communication', 'Cahier de communication'), ('journal_classe', 'Journal de classe'), ('autre', 'Autre')], max_length=50, verbose_name='Type de frais'),
        ),
        migrations.AlterField(
            model_name='tariffrais',
            name='type_frais',
            field=models.CharField(choices=[('inscription', "Frais d'inscription"), ('minerval', 'Minerval'), ('uniforme', 'Uniforme'), ('examen', "Frais d'examen"), ('activite', 'Activité parascolaire'), ('ecusson', 'Ecusson'), ('tenasosp', 'Tenasosp'), ('dissertation', 'Dissertation'), ('exetat', 'Exetat'), ('cahier_communication', 'Cahier de communication'), ('journal_classe', 'Journal de classe'), ('autre', 'Autre')], max_length=50, verbose_name='Type de frais'),
        ),
    ]
