# Generated by Django 6.0.3 on 2026-08-18 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0011_eleve_annee_scolaire'),
        ('frais_scolaires', '0004_reference_models_for_fees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeJeton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Code du jeton')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('date_utilisation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'utilisation")),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frais_scolaires.anneescolaire', verbose_name='Année scolaire')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.classe', verbose_name='Classe')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jetons_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eleves.eleve', verbose_name='Élève')),
                ('trimestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frais_scolaires.trimestre', to_field='numero', verbose_name='Trimestre')),
                ('type_frais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frais_scolaires.typefrais', to_field='code', verbose_name='Type de frais')),
                ('utilise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jetons_utilises', to=settings.AUTH_USER_MODEL, verbose_name='Utilisé par')),
            ],
            options={
                'verbose_name': 'Code jeton',
                'verbose_name_plural': 'Codes jeton',
                'ordering': ['-date_creation'],
            },
        ),
    ]
