# Generated by Django 6.0.3 on 2026-08-18 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0011_eleve_annee_scolaire'),
        ('frais_scolaires', '0005_code_jeton'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fraisscolaire',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='codejeton',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='eleve',
        ),
        migrations.AddField(
            model_name='codejeton',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.niveauclasse', to_field='code', verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='fraisscolaire',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.niveauclasse', to_field='code', verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.niveauclasse', to_field='code', verbose_name='Niveau'),
        ),
        migrations.RemoveField(
            model_name='fraisscolaire',
            name='eleve',
        ),
    ]
