# Generated by Django 5.2.13 on 2026-04-21 13:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('primaire', 'Primaire'), ('humanite', 'Humanité')], max_length=20)),
                ('classe_primaire', models.CharField(blank=True, choices=[('1ère', '1ère année'), ('2ème', '2ème année'), ('3ème', '3ème année'), ('4ème', '4ème année'), ('5ème', '5ème année'), ('6ème', '6ème année')], max_length=20, null=True)),
                ('classe_humanite', models.CharField(blank=True, choices=[('7ème', '7ème année'), ('8ème', '8ème année'), ('1ère humanité', '1ère humanité'), ('2ème humanité', '2ème humanité'), ('3ème humanité', '3ème humanité'), ('4ème humanité', '4ème humanité')], max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('post_nom', models.CharField(max_length=100, verbose_name='Post-nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Numéro de téléphone invalide')], verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Email invalide')], verbose_name='Email')),
                ('matricule', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Matricule')),
                ('date_inscription', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves/photos/', verbose_name='Photo')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('diplômé', 'Diplômé')], default='actif', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.classe', verbose_name='Classe')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'post_nom', 'prenom'],
            },
        ),
    ]
