# Generated by Django 5.2.13 on 2026-04-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='classe_humanite',
            field=models.CharField(blank=True, choices=[('7eme', '7ème année'), ('8eme', '8ème année'), ('1ere_humanite', '1ère humanité'), ('2eme_humanite', '2ème humanité'), ('3eme_humanite', '3ème humanité'), ('4eme_humanite', '4ème humanité')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='classe_primaire',
            field=models.CharField(blank=True, choices=[('1ere', '1ère année'), ('2eme', '2ème année'), ('3eme', '3ème année'), ('4eme', '4ème année'), ('5eme', '5ème année'), ('6eme', '6ème année')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eleves.classe', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('diplome', 'Diplômé')], default='actif', max_length=20, verbose_name='Statut'),
        ),
    ]
