# Generated by Django 5.2.13 on 2026-04-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_alter_classe_classe_humanite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='section',
            field=models.CharField(blank=True, choices=[('chimie_biologie', 'Chimie Biologie'), ('pedagogie', 'Pédagogie'), ('electricite', 'Électricité'), ('coupe_couture', 'Coupe et Couture'), ('latin_philo', 'Latin Philo'), ('commerciale', 'Commerciale'), ('generale', 'Générale')], max_length=50, null=True, verbose_name='Section (Humanité)'),
        ),
    ]
