# Generated by Django 4.2.29 on 2026-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_classe_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='classe_maternel',
            field=models.CharField(blank=True, choices=[('1ere_maternelle', '1ère maternelle'), ('2eme_maternelle', '2ème maternelle'), ('3eme_maternelle', '3ème maternelle')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='est_masp',
            field=models.BooleanField(default=False, verbose_name='Est membre de la Mutualité MASP'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('maternel', 'Maternel'), ('primaire', 'Primaire'), ('humanite', 'Humanité')], max_length=20),
        ),
    ]
