# Generated by Django 5.2.13 on 2026-04-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0004_classe_classe_maternel_eleve_est_masp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='lieu_de_naissance',
            field=models.CharField(blank=True, default='non renseigné', max_length=200, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='section',
            field=models.CharField(blank=True, choices=[('chimie_biologie', 'Chimie Biologie'), ('pedagogie', 'Pédagogie'), ('electricite', 'Électricité'), ('coupe_couture', 'Coupe et Couture'), ('latin_philo', 'Latin Philo'), ('commerciale', 'Commerciale'), ('construction', 'Construction'), ('mecanique_auto', 'Mécanique Auto')], max_length=50, null=True, verbose_name='Section (Humanité)'),
        ),
    ]
