# Generated by Django 5.2.13 on 2026-04-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0005_eleve_lieu_de_naissance_alter_classe_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='lieu_de_naissance',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu de naissance'),
        ),
    ]
