# Generated by Django 5.2.13 on 2026-04-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0006_alter_eleve_lieu_de_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='lieu_de_naissance',
            field=models.CharField(blank=True, default='Aucun', max_length=200, null=True, verbose_name='Lieu de naissance'),
        ),
    ]
