# Generated by Django 6.0.3 on 2026-07-30 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0009_reference_models_for_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eleves.sectionhumanite', to_field='code', verbose_name='Section (Humanité)'),
        ),
    ]
