# Generated by Django 5.2.13 on 2026-04-22 02:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code dépense')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la dépense')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FC)')),
                ('date_depense', models.DateField(default=django.utils.timezone.now, verbose_name='Date de dépense')),
                ('beneficiaire', models.CharField(max_length=200, verbose_name='Bénéficiaire')),
                ('mode_paiement', models.CharField(choices=[('cash', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], max_length=20, verbose_name='Mode de paiement')),
                ('justificatif', models.ImageField(blank=True, null=True, upload_to='depenses/justificatifs/', verbose_name='Justificatif')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depense.categoriedepense', verbose_name='Catégorie')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPrevisionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=20, verbose_name='Année scolaire')),
                ('montant_prevu', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant prévu (FC)')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depense.categoriedepense')),
            ],
            options={
                'verbose_name': 'Budget prévisionnel',
                'verbose_name_plural': 'Budgets prévisionnels',
                'unique_together': {('categorie', 'annee_scolaire')},
            },
        ),
    ]
