# Generated by Django 4.2.29 on 2026-04-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriedepense',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
